export const keyof = function <T>(obj: T): (keyof T)[] {
    return Object.keys(obj) as (keyof T)[]
}

export const skilltypes = {
    boost: {
        name: "boost",
        nameja: "スキブ",
        atype: "l",
        boost: 0.2,
        cover: 1,
    },
    srboost: {
        name: "srboost",
        nameja: "SRスキブ",
        atype: "m",
        boost: 0.1,
        cover: 1,
    },
    symfony: {
        name: "symfony",
        nameja: "シンフォ",
        atype: "m",
        boost: 0.5,
        cover: 1,
    },
    combona: {
        name: "combona",
        nameja: "コンボナ",
        combo: 18,
        atype: "m",
    },
    unison: {
        name: "unison",
        nameja: "ユニゾン",
        atype: "m",
        boost: 0.5,
        hastarget: true,
    },
    motif: {
        name: "motif",
        nameja: "モチーフ",
        atype: "m",
        score: 17,
    },

    slideact: {
        name: "slideact",
        nameja: "スラアク",
        atype: "ml",
        score: 10,
        slide: 40,
    },
    support: {
        name: "support",
        nameja: "サポート",
        atype: "s",
        support: 3,
    },
    rsupport: {
        name: "rsupport",
        nameja: "Rサポ",
        atype: "m",
        support: 1,
    },
    tuning: {
        name: "tuning",
        nameja: "チューン",
        atype: "m",
        combo: 12,
        support: 2,
    },
    synergy: {
        name: "synergy",
        nameja: "シナジー",
        atype: "m",
        score: 16,
        combo: 15,
        heal: 1,
    },
    coode: {
        name: "coode",
        nameja: "コーデ",
        atype: "m",
        score: 10,
        combo: 15,
    },
    concent: {
        name: "concent",
        nameja: "コンセ",
        atype: "m",
        score: 22,
    },

    heal: {
        name: "heal",
        nameja: "回復",
        atype: "ms",
        heal: 3,
    },
    guard: {
        name: "guard",
        nameja: "ダメガ",
        atype: "m",
        heal: 0,
        guard: 1,
        isheal: true,
    },
    ssrguard: {
        name: "ssrguard",
        nameja: "ダメガ",
        atype: "ml",
        heal: 0,
        guard: 1,
        isheal: true,
    },
    allround: {
        name: "allround",
        nameja: "オルラン",
        atype: "ms",
        combo: 13,
        heal: 1,
    },
    encore: {
        name: "encore",
        nameja: "アンコ",
        atype: "s",
    },
    refrain: {
        name: "refrain",
        nameja: "リフレ",
        atype: "m",
    },
    magic: {
        name: "magic",
        nameja: "マジック",
        atype: "sp",
    },
    scoregenre: {
        name: "scoregenre",
        nameja: "スコア系",
        atype: "m",
    },
    combogenre: {
        name: "combogenre",
        nameja: "コンボナ系",
        atype: "m",
    },
    bothgenre: {
        name: "bothgenre",
        nameja: "コーデ系",
        atype: "m",
    },
    none: {
        name: "none",
        nameja: "なし",
        atype: "m",
    },
} as const

export type IskillName = keyof typeof skilltypes

export const atimes = {
    l: {
        "7無": 0,
        "7高": 12,
        "8高": 15,
        "10高": 18,
    },
    ml: {
        "7無": 0,
        "7高": 12,
        "9高": 15,
        "11高": 18,
    },
    m: {
        "4高": 6,
        "6中": 9,
        "7無": 0,
        "7高": 9,
        "7中": 12,
        "8中": 9,
        "9高": 12,
        "9中": 15,
        "11高": 15,
        "11中": 18,
        "13高": 18,
        "9低": 12,
        "11低": 15,
        "13低": 18,
    },
    ms: {
        "5高": 6,
        "7中": 9,
        "7無": 0,
        "8高": 9,
        "9中": 12,
        "11高": 12,
        "13高": 15,
        "13中": 18,
    },
    s: {
        "7無": 0,
        "9中": 9,
        "9高": 9,
        "12高": 12,
        "12中": 12,
        "15高": 15,
        "15中": 15,
        "18高": 18,
        "18中": 18,
    },
    sp: {
        "12中": 15,
        "7無": 0,
    },
} as const
export type Iatype = keyof typeof atimes

export type Iattr = "cu" | "co" | "pa"
export type Iatime = keyof typeof atimes

export type IidolProfile = readonly [string, Iattr, number, string, IskillName]

export const cards: { [k: string]: readonly IidolProfile[] } = {
    symfony: [
        ["シンフォ7高cu", "cu", 7, "高", "symfony"],
        ["シンフォ7高co", "co", 7, "高", "symfony"],
        ["シンフォ7高pa", "pa", 7, "高", "symfony"],
        ["シンフォ9高cu", "cu", 9, "高", "symfony"],
        ["シンフォ9高co", "co", 9, "高", "symfony"],
        ["シンフォ9高pa", "pa", 9, "高", "symfony"],
        ["シンフォ11高cu", "cu", 11, "高", "symfony"],
        ["シンフォ11高co", "co", 11, "高", "symfony"],
        ["シンフォ11高pa", "pa", 11, "高", "symfony"],
    ],

    boost: [
        ["スキブ7高cu", "cu", 7, "高", "boost"],
        ["スキブ7高co", "co", 7, "高", "boost"],
        ["スキブ7高pa", "pa", 7, "高", "boost"],
        ["スキブ8高cu", "cu", 8, "高", "boost"],
        ["スキブ8高co", "co", 8, "高", "boost"],
        ["スキブ8高pa", "pa", 8, "高", "boost"],
        ["スキブ10高cu", "cu", 10, "高", "boost"],
        ["スキブ10高co", "co", 10, "高", "boost"],
        ["スキブ10高pa", "pa", 10, "高", "boost"],
        ["srスキブ7高cu", "cu", 7, "高", "srboost"],
        ["srスキブ7高co", "co", 7, "高", "srboost"],
        ["srスキブ7高pa", "pa", 7, "高", "srboost"],
        ["srスキブ9高cu", "cu", 9, "高", "srboost"],
        ["srスキブ9高co", "co", 9, "高", "srboost"],
        ["srスキブ9高pa", "pa", 9, "高", "srboost"],
        ["srスキブ11高cu", "cu", 11, "高", "srboost"],
        ["srスキブ11高co", "co", 11, "高", "srboost"],
        ["srスキブ11高pa", "pa", 11, "高", "srboost"],
    ],

    support: [
        ["サポート9高cu", "cu", 9, "高", "support"],
        ["サポート12高co", "co", 12, "高", "support"],
        ["サポート15高pa", "pa", 15, "高", "support"],
        ["サポート9高co", "co", 9, "高", "support"],
        ["サポート12高pa", "pa", 12, "高", "support"],
        ["サポート15高cu", "cu", 15, "高", "support"],
        ["サポート9高pa", "pa", 9, "高", "support"],
        ["サポート12高cu", "cu", 12, "高", "support"],
        ["サポート15高co", "co", 15, "高", "support"],
    ],

    heal: [
        ["回復7中", "cu", 7, "中", "heal"],
        ["回復8高", "cu", 8, "高", "heal"],
        ["回復9中", "cu", 9, "中", "heal"],
        ["回復11高", "cu", 11, "高", "heal"],
        ["回復13高", "cu", 13, "高", "heal"],
        ["回復育成", "cu", 7, "無", "heal"],
    ],

    guard: [
        ["ssrダメガ7高cu", "cu", 7, "高", "ssrguard"],
        ["ssrダメガ7高co", "co", 7, "高", "ssrguard"],
        ["ssrダメガ7高pa", "pa", 7, "高", "ssrguard"],
        ["ダメガ7中cu", "cu", 7, "中", "guard"],
        ["ダメガ7中co", "co", 7, "中", "guard"],
        ["ダメガ7中pa", "pa", 7, "中", "guard"],
        ["ダメガ7高cu", "cu", 7, "高", "guard"],
        ["ダメガ7高co", "co", 7, "高", "guard"],
        ["ダメガ7高pa", "pa", 7, "高", "guard"],
        ["ダメガ9中cu", "cu", 9, "中", "guard"],
        ["ダメガ9中co", "co", 9, "中", "guard"],
        ["ダメガ9中pa", "pa", 9, "中", "guard"],
        ["ダメガ9高cu", "cu", 9, "高", "guard"],
        ["ダメガ9高co", "co", 9, "高", "guard"],
        ["ダメガ9高pa", "pa", 9, "高", "guard"],
        ["ダメガ11中cu", "cu", 11, "中", "guard"],
        ["ダメガ11中co", "co", 11, "中", "guard"],
        ["ダメガ11中pa", "pa", 11, "中", "guard"],
        ["ダメガ11高cu", "cu", 11, "高", "guard"],
        ["ダメガ11高co", "co", 11, "高", "guard"],
        ["ダメガ11高pa", "pa", 11, "高", "guard"],
        ["ダメガ8中cu", "cu", 8, "中", "guard"],
    ],

    synergy: [
        ["シナジー7高cu", "cu", 7, "高", "synergy"],
        ["シナジー7高co", "co", 7, "高", "synergy"],
        ["シナジー7高pa", "pa", 7, "高", "synergy"],
        ["シナジー9高cu", "cu", 9, "高", "synergy"],
        ["シナジー9高co", "co", 9, "高", "synergy"],
        ["シナジー9高pa", "pa", 9, "高", "synergy"],
        ["シナジー11高cu", "cu", 11, "高", "synergy"],
        ["シナジー11高co", "co", 11, "高", "synergy"],
        ["シナジー11高pa", "pa", 11, "高", "synergy"],
    ],

    tuning: [
        ["チューニング7高cu", "cu", 7, "高", "tuning"],
        ["チューニング7高co", "co", 7, "高", "tuning"],
        ["チューニング7高pa", "pa", 7, "高", "tuning"],
        ["チューニング9高cu", "cu", 9, "高", "tuning"],
        ["チューニング9高co", "co", 9, "高", "tuning"],
        ["チューニング9高pa", "pa", 9, "高", "tuning"],
        ["チューニング11高cu", "cu", 11, "高", "tuning"],
        ["チューニング11高co", "co", 11, "高", "tuning"],
        ["チューニング11高pa", "pa", 11, "高", "tuning"],
        ["チューニング11中cu", "cu", 11, "中", "tuning"],
        ["チューニング11中co", "co", 11, "中", "tuning"],
        ["チューニング11中pa", "pa", 11, "中", "tuning"],
        ["チューニング13高cu", "cu", 13, "高", "tuning"],
        ["チューニング13高co", "co", 13, "高", "tuning"],
        ["チューニング13高pa", "pa", 13, "高", "tuning"],
    ],

    encore: [
        ["アンコ9中cu", "cu", 9, "中", "encore"],
        ["アンコ9中co", "co", 9, "中", "encore"],
        ["アンコ9中pa", "pa", 9, "中", "encore"],

        ["アンコ12中cu", "cu", 12, "高", "encore"],
        ["アンコ12高co", "co", 12, "高", "encore"],
        ["アンコ12中pa", "pa", 12, "高", "encore"],

        ["アンコ15中cu", "cu", 15, "高", "encore"],
        ["アンコ15中co", "co", 15, "高", "encore"],
        ["アンコ15高pa", "pa", 15, "高", "encore"],

        ["アンコ18中cu", "cu", 18, "中", "encore"],
        ["アンコ18中co", "co", 18, "中", "encore"],
        ["アンコ18中pa", "pa", 18, "中", "encore"],
    ],

    motif: [
        ["モチーフ7高cu", "cu", 7, "高", "motif"],
        ["モチーフ7高co", "co", 7, "高", "motif"],
        ["モチーフ7高pa", "pa", 7, "高", "motif"],
        ["モチーフ9高cu", "cu", 9, "高", "motif"],
        ["モチーフ9高co", "co", 9, "高", "motif"],
        ["モチーフ9高pa", "pa", 9, "高", "motif"],
        ["モチーフ11高cu", "cu", 11, "高", "motif"],
        ["モチーフ11高co", "co", 11, "高", "motif"],
        ["モチーフ11高pa", "pa", 11, "高", "motif"],
    ],

    refrain: [
        ["リフレイン7高cu", "cu", 7, "高", "refrain"],
        ["リフレイン7高co", "co", 7, "高", "refrain"],
        ["リフレイン7高pa", "pa", 7, "高", "refrain"],
        ["リフレイン9高cu", "cu", 9, "高", "refrain"],
        ["リフレイン9高co", "co", 9, "高", "refrain"],
        ["リフレイン9高pa", "pa", 9, "高", "refrain"],
        ["リフレイン11高cu", "cu", 11, "高", "refrain"],
        ["リフレイン11高co", "co", 11, "高", "refrain"],
        ["リフレイン11高pa", "pa", 11, "高", "refrain"],
    ],

    magic: [
        ["マジック12中cu", "cu", 12, "中", "magic"],
        ["マジック12中co", "co", 12, "中", "magic"],
        ["マジック12中pa", "pa", 12, "中", "magic"],
        ["マジック12中cu2", "cu", 12, "中", "magic"],
        ["マジック12中co2", "co", 12, "中", "magic"],
        ["マジック12中pa2", "pa", 12, "中", "magic"],
        ["マジック12中cu3", "cu", 12, "中", "magic"],
        ["マジック12中co3", "co", 12, "中", "magic"],
        ["マジック12中pa3", "pa", 12, "中", "magic"],
    ],

    scoregenre: [
        ["コンセ7高cu", "cu", 7, "高", "concent"],
        ["コンセ7高co", "co", 7, "高", "concent"],
        ["コンセ7高pa", "pa", 7, "高", "concent"],
        ["コンセ9高cu", "cu", 9, "高", "concent"],
        ["コンセ9高co", "co", 9, "高", "concent"],
        ["コンセ9高pa", "pa", 9, "高", "concent"],
        ["コンセ11高cu", "cu", 11, "高", "concent"],
        ["コンセ11高co", "co", 11, "高", "concent"],
        ["コンセ11高pa", "pa", 11, "高", "concent"],
        ["コンセ11中cu", "cu", 11, "中", "concent"],
        ["コンセ11中co", "co", 11, "中", "concent"],
        ["コンセ11中pa", "pa", 11, "中", "concent"],
        ["コンセ13高cu", "cu", 13, "高", "concent"],
        ["コンセ13高co", "co", 13, "高", "concent"],
        ["コンセ13高pa", "pa", 13, "高", "concent"],
        ["スラアク7高cu", "cu", 7, "高", "slideact"],
        ["スラアク7高co", "co", 7, "高", "slideact"],
        ["スラアク7高pa", "pa", 7, "高", "slideact"],
        ["スラアク9高cu", "cu", 9, "高", "slideact"],
        ["スラアク9高co", "co", 9, "高", "slideact"],
        ["スラアク9高pa", "pa", 9, "高", "slideact"],
        ["スラアク11高cu", "cu", 11, "高", "slideact"],
        ["スラアク11高co", "co", 11, "高", "slideact"],
        ["スラアク11高pa", "pa", 11, "高", "slideact"],
    ],

    combogenre: [
        ["オルラン5高cu", "cu", 5, "高", "allround"],
        ["オルラン5高co", "co", 5, "高", "allround"],
        ["オルラン5高pa", "pa", 5, "高", "allround"],
        ["オルラン8高cu", "cu", 8, "高", "allround"],
        ["オルラン8高co", "co", 8, "高", "allround"],
        ["オルラン8高pa", "pa", 8, "高", "allround"],
        ["オルラン9中cu", "cu", 9, "中", "allround"],
        ["オルラン9中co", "co", 9, "中", "allround"],
        ["オルラン9中pa", "pa", 9, "中", "allround"],
        ["オルラン11高cu", "cu", 11, "高", "allround"],
        ["オルラン11高co", "co", 11, "高", "allround"],
        ["オルラン11高pa", "pa", 11, "高", "allround"],
        ["オルラン13中cu", "cu", 13, "中", "allround"],
        ["オルラン13中co", "co", 13, "中", "allround"],
        ["オルラン13中pa", "pa", 13, "中", "allround"],
        ["コンボナ4高cu", "cu", 4, "高", "combona"],
        ["コンボナ6中cu", "cu", 6, "中", "combona"],
        ["コンボナ7高cu", "cu", 7, "高", "combona"],
        ["コンボナ7中cu", "cu", 7, "中", "combona"],
        ["コンボナ9高cu", "cu", 9, "高", "combona"],
        ["コンボナ9中cu", "cu", 9, "中", "combona"],
        ["コンボナ11高cu", "cu", 11, "高", "combona"],
        ["コンボナ11中cu", "cu", 11, "中", "combona"],
        ["コンボナ13高cu", "cu", 13, "高", "combona"],
    ],

    bothgenre: [
        ["コーデ7高cu", "cu", 7, "高", "coode"],
        ["コーデ7高co", "co", 7, "高", "coode"],
        ["コーデ7高pa", "pa", 7, "高", "coode"],
        ["コーデ9高cu", "cu", 9, "高", "coode"],
        ["コーデ9高co", "co", 9, "高", "coode"],
        ["コーデ9高pa", "pa", 9, "高", "coode"],
        ["コーデ11高cu", "cu", 11, "高", "coode"],
        ["コーデ11高co", "co", 11, "高", "coode"],
        ["コーデ11高pa", "pa", 11, "高", "coode"],
    ],
} as const

export const SCORES_NORMAL = {
    "Unlock Starbeat[mas]": "./score/us.json",
    "サマカニ!![mas+]": "./score/samacani.json",
    "輝く世界の魔法[witch]": "./score/kagaseka.json",
    "ドレミファクトリー！[pro]": "./score/doremi.json",
    "ミラーボール・ラブ[mas]": "./score/mirror.json",
    "ビートシューター[mas]": "./score/beat_new.json",
}

export const SCORES_GRAND = {
    "Stage Bye Stage": "./score/sbs.json",
    "M@GIC": "./score/magic.json",
    星環世界: "./score/seikan.json",
}

export const LIFE_DEFAULT = 264
export const MUSIC_MAXTIME = 140
